### ISSUE TITLE
NullReferenceException after restoring state

### ISSUE THREAD

**Issue by duke-bartholomew** [LGouellec/kafka-streams-dotnet#200]
Description
===========
Topology with some statefull logic inside a Transformer (kafka-streams-dotnet version 1.4.0-RC3)
Topology starts up fine and populates the state. (entries appear on the underlying Kafka state topic)
When I would now kill the pod running the KafkaStreams topology, it restarts (all fine), KafkaStreams starts up all fine, but then all of a sudden a NullReferenceException happens when trying to manipulate the state-store.
(state-store = `InMemoryKeyValueStore`)

```
ERROR Streamiz.Kafka.Net.Processors.Internal.TaskManager - Failed to process stream task 0-1 due to the following error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Streamiz.Kafka.Net.State.Logging.ChangeLoggingKeyValueBytesStore.Publish(Bytes key, Byte[] value)
   at Streamiz.Kafka.Net.State.Logging.ChangeLoggingKeyValueBytesStore.Delete(Bytes key)
   at Streamiz.Kafka.Net.State.Metered.MeteredKeyValueStore`2.<>c__DisplayClass27_0.<Delete>b__0()
   at Streamiz.Kafka.Net.Crosscutting.ActionHelper.MeasureLatency[T](Func`1 actionToMeasure, Sensor sensor)
   at Streamiz.Kafka.Net.State.Metered.MeteredKeyValueStore`2.Delete(K key)
```

My test topology consists out of following components:
- 1 source topic (4 partitions)
- simple filter
- transformer: just issues PUT and DELETE actions on the mounted state-store
- no output topic

When deploying multiple instances of the topology, eventually it makes it to running state and starts processing correctly
(after a few crashes with above exception), so it _looks_ like the producer lying underneath the state-stores does not get initialized in time when switching to "normal processing".

This error also only happens when there is indeed state to restore.
When starting the topology _clean_ (no data in the state-stores yet), then everything works fine.

How to reproduce
================
I was not able to directly reproduce the above error on a local Kafka setup (on my PC).
The above exception shows up on our Kubernetes cluster with Kafka running in SSL setup (with strict ACLs towards the clients) which might indicate a timing issue?

**Comment by LGouellec** [comment]
Hi @duke-bartholomew,

I was not able to reproduce the above error with a local docker-compose too. 
Can you add the full stacktrace please before throwing the NPE please ? 

Best regards,

**Comment by LGouellec** [comment]
@duke-bartholomew 

Could you show your implementation of `ParkingSessions.NET.ObservationTimeExtractor` please ? 

Best regards,

**Comment by duke-bartholomew** [comment]
```
return (record.Message.Value as Model)?.Timestamp() ?? -1;
```
which would basically be (in this case) the `observation-time: 1668616859000` from the log above the exception.

**Comment by LGouellec** [comment]
Thanks for your inputs @duke-bartholomew.

Is it possible to share your transformer implementation ? Of course, keep the technical code but remove confidential things maybe.

Thanks

**Comment by LGouellec** [comment]
@duke-bartholomew , 

Do you enable `config.ParallelProcessing` ? 

Best regards,

**Comment by duke-bartholomew** [comment]
@LGouellec 
I did not configure `ParallelProcessing`, so it's set to the default value: `false`

DEBUG level log file:
[crash.log.tar.gz](https://github.com/LGouellec/kafka-streams-dotnet/files/10039840/crash.log.tar.gz)

It's all a test project to basically get some feeling with the kafkastreams.NET library, so there's no confidential stuff in there ...
My transformer:
```
public class MyStatefulTransformer: ITransformer<string, Model, string, Model> {
    private static readonly ILogger log = Settings.Factory.CreateLogger(typeof(MyStatefulTransformer));
    
    private IKeyValueStore<string, string> store;
    private readonly string storeName;

    public MyStatefulTransformer(string storeName) {
        this.storeName = storeName;
    }
    
    public void Init(ProcessorContext context) {
        store = (IKeyValueStore<string, string>)context.GetStateStore(storeName);
    }

    public Record<string, Model> Process(Record<string, Model> record) {
        log.LogDebug("PROCESS RECORD - tpo:{Topic}:{Partition}@{Offset}, key:{Key}",
            record.TopicPartitionOffset.Topic,
            record.TopicPartitionOffset.Partition,
            record.TopicPartitionOffset.Offset,
            record.Key
        );

        var storeKey = $"{record.Value.group}/{record.Value.id}";

        switch (record.Value.status) {
            case Status.Free:
                log.LogInformation("remove from state-store - key:{Key}", storeKey);
                store.Delete(storeKey);
                break;
            
            case Status.Occupied:
                log.LogInformation("add to state-store - key:{Key}, value:{Value}", storeKey, record.Value.iso8601time);
                store.Put(storeKey, record.Value.iso8601time);
                break;
            
            default:
                log.LogWarning("unknown status: {Status} -- Ignore!", record.Value.status);
                break;
        }
        
        return record;
    }

    public void Close() {
        log.LogDebug("CLOSE CALLED");
    }
}
```

Little snippet from the content of my changelog topic (Key   Value):
```
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S026        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S007        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S004        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S025        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S009        11/17/2022 12:26:38
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S022        11/17/2022 12:26:38
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S015        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S008        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S010        11/17/2022 12:26:46
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S006        11/17/2022 12:26:46
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S026        11/17/2022 12:26:47
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S016        11/17/2022 12:26:47
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S000        11/17/2022 12:26:48
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S025        11/17/2022 12:26:50
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S018        11/17/2022 12:26:51
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S024        11/17/2022 12:26:52
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S021        11/17/2022 12:26:53
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S000        null
urn:gspt:ngsi-ld:ParkingGroup:iotb:pl:G000/urn:gspt:ngsi-ld:ParkingSpot:iotb:pb:G000S018        null
```

**Comment by duke-bartholomew** [comment]
Hi @LGouellec,

Did a couple more tests.
It looks like the Task that is still in process of restoring state actually gets records to process.
Because it's still restoring, the context == null ? (which makes sense as I assume the partition for that task should be _paused_ on the consumer?)

I try .. catch'ed the store.put and store.delete actions.
Eventually the topology goes into stable running state (when I swallow the exceptions) -- but, of course, I have data-loss now as I was not able to process the messages in my transformer ... anyway ...

```
2022-11-18 09:50:43,974 [dummy.parkingprocessor-dotnet-b69a6a0b-b4ed-47e7-b873-cc1a90d3622f-stream-thread-0] ERROR ParkingSessions.NET.MyStatefulTransformer - !!!!!!!!!! BOOM [TASK: 0-2] !!!!!!!!!!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Streamiz.Kafka.Net.State.Logging.ChangeLoggingKeyValueBytesStore.Publish(Bytes key, Byte[] value)
   at Streamiz.Kafka.Net.State.Logging.ChangeLoggingKeyValueBytesStore.Put(Bytes key, Byte[] value)
   at Streamiz.Kafka.Net.State.Metered.MeteredKeyValueStore`2.<>c__DisplayClass24_0.<Put>b__0()
   at Streamiz.Kafka.Net.Crosscutting.ActionHelper.MeasureLatency(Action actionToMeasure, Sensor sensor)
   at Streamiz.Kafka.Net.State.Metered.MeteredKeyValueStore`2.Put(K key, V value)
   at ParkingSessions.NET.MyStatefulTransformer.<Process>b__6_0(Record`2 record) in /build/src/MyStatefulTransformer.cs:line 63
   at ParkingSessions.NET.MyStatefulTransformer.Process(Record`2 record) in /build/src/MyStatefulTransformer.cs:line 75
2022-11-18 09:50:45,029 [dummy.parkingprocessor-dotnet-b69a6a0b-b4ed-47e7-b873-cc1a90d3622f-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.Internal.StoreChangelogReader - Finished restoring changelog my-state to store dummy.parkingprocessor-dotnet-my-state-changelog [[2]] with a total number of 19474 records
2022-11-18 09:50:45,129 [dummy.parkingprocessor-dotnet-b69a6a0b-b4ed-47e7-b873-cc1a90d3622f-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|2] Task 0-2 state transition from RESTORING to RUNNING
2022-11-18 09:50:45,130 [dummy.parkingprocessor-dotnet-b69a6a0b-b4ed-47e7-b873-cc1a90d3622f-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|2] Restored and ready to run
2022-11-18 09:50:45,132 [dummy.parkingprocessor-dotnet-b69a6a0b-b4ed-47e7-b873-cc1a90d3622f-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamThread - Restoration took 3204ms for all tasks 0-2,0-1,0-0
```

The _BOOM_ log is always happening on the same task (Task: 2), the one that's still restoring ....

**Comment by LGouellec** [comment]
@duke-bartholomew , 

I reproduced the issue locally. It's not a state restoration problem. The null object is `context.RecordContext`
The problem is the instance of the transformer = It's the same instance for all partitions, so I think I have a concurrency problem.

I will try to release a new RC this afternoon with a fix.

**Comment by duke-bartholomew** [comment]
@LGouellec 
I tried to follow the code, so basically this is it, right?
```
public IProcessor<K, V> Get() => (IProcessor<K, V>) new KStreamTransformer<K, V, K1, V1>(this.transformerSupplier, this.changeKey);
```
the transformerSupplier is not a true _supplier_ in that sense that it only contains a single instance of the transformer instead of creating a new one when needed.

so it should then be something in the gist like this?
```
public IProcessor<K, V> Get() => (IProcessor<K, V>) new KStreamTransformer<K, V, K1, V1>(this.transformerSupplier.Get(), this.changeKey);  // with KStreamTransformer wrapping the Transformer instead of the supplier ?
```

**Comment by LGouellec** [comment]
@duke-bartholomew , 

Yes exactly ! I will fix asap

**Comment by LGouellec** [comment]
@duke-bartholomew ,

I released a new pre-release version `1.4.0-RC4` which fix this issue. 

Feel free to test and close the issue if it's ok.

Thanks,

**Comment by duke-bartholomew** [comment]
Hi @LGouellec 
Thanks for the effort :+1: 

I quickly ran some tests:
- starting the topology now works as expected: :heavy_check_mark: 
- rebalancing (scale up from 1 instance to 3 instances): :heavy_check_mark: 
- rebalancing (scale down from 3 instances to 1 instance) : :boom: 
  Here I still see some issues.
  At first glance it looks like the state does not get restored on the reassigned partitions.
```
2022-11-18 16:45:51,699 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|1] Task 0-1 state transition from SUSPENDED to CREATED
2022-11-18 16:45:51,699 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|0] Task 0-0 state transition from SUSPENDED to CREATED
2022-11-18 16:45:51,699 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamThread - stream-thread[dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] State transition from RUNNING to PARTITIONS_ASSIGNED
2022-11-18 16:45:51,699 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.KafkaStream - stream-application[dummy.parkingprocessor-dotnet] State transition from RUNNING to REBALANCING
2022-11-18 16:45:51,699 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Kafka.Internal.StreamsRebalanceListener - Partition assignment took 00:00:00.0059467 ms.
	Currently assigned active tasks: 0-0,0-1,0-2
	Revoked assigned active tasks: 

2022-11-18 16:45:51,808 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  ParkingSessions.NET.ObservationTimeExtractor - extract timestamp - tpo: dummy.parkingspot.events:[1]@3796508, record-time: 1668789905488, partition-time: -1, observation-time: 1668789905000
2022-11-18 16:45:51,808 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  ParkingSessions.NET.ObservationTimeExtractor - extract timestamp - tpo: dummy.parkingspot.events:[0]@3798701, record-time: 1668789903226, partition-time: -1, observation-time: 1668789903000
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamThread - stream-thread[dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] State transition from PARTITIONS_ASSIGNED to RUNNING
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.KafkaStream - stream-application[dummy.parkingprocessor-dotnet] State transition from REBALANCING to RUNNING
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.Internal.ProcessorStateManager - Initializing to the starting offset for changelog dummy.parkingprocessor-dotnet-my-state-changelog [[0]] of in-memory state store my-state
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|0] Task 0-0 state transition from CREATED to RESTORING
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|0] Restoration will start soon.
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.Internal.ProcessorStateManager - Initializing to the starting offset for changelog dummy.parkingprocessor-dotnet-my-state-changelog [[1]] of in-memory state store my-state
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|1] Task 0-1 state transition from CREATED to RESTORING
2022-11-18 16:45:51,809 [dummy.parkingprocessor-dotnet-680afeeb-8e4e-43b8-bcfa-e1cac785c9c1-stream-thread-0] INFO  Streamiz.Kafka.Net.Processors.StreamTask - stream-task[0|1] Restoration will start soon.
```
After that I can see Task 2 processing data, but nothing on the other 2 tasks. They get initialized, but I don't see them restoring state and starting to process data ...

This was a very quick test ... I'll do some more thorough testing later ...

**Comment by duke-bartholomew** [comment]
@LGouellec 

When looking trough the debug logs and backtracking trough the code I encountered this in `StoreChangelogReader::InitChangelogs`:
```
            // TODO : call trigger onRestoreStart(...)
```
This is exactly the code called in case I scale down, so when the partitions get re-assigned to the 1 running instance.

I have hit unsupported functionality?

**Comment by LGouellec** [comment]
@duke-bartholomew ,

No, this TODO is just Streamiz does not support to subscribe restoration event from KafkaStream like JAVA do it.

But maybe the issue is based on this workflow : 

Suppose the topic topic1 with 3 partitions

Instance 1 : topic1:0,topic1:1,topic1:2 restore and process.
Everything ok

Scale up to 2, so
Instance 1 : topic1:0,topic1:1 (nothing change), topic1:2 switch to SUSPEND state
Instance 2 : topic1:2 restore and process
Everything ok

Scale down, so
Instance 1 : topic1:0,topic1:1 (nothing change), topic1:2 switch from SUSPEND to RESUME and here I'm not sure that the task restore the changelog before processing new messages. 

I will try to reproduce this issue beginning next week.

Hope it's clear

**Comment by duke-bartholomew** [comment]
@LGouellec 
"Instance 1 : topic1:0,topic1:1 (nothing change), topic1:2 switch from SUSPEND to RESUME and here I'm not sure that the task restore the changelog before processing new messages."

That is exactly what I see happening.
Instead of restoring state, messages from those partitions are still consumed, and added to the internal queue (up till 1000 entries and then it all halts).  The processors for those partitions are not triggered, but it looks like the system is waiting for the restore of those partitions to complete while it has never started ...

**Comment by LGouellec** [comment]
Hi @duke-bartholomew , 

I fix the last issue. `1.4.0-rc5` contains this fix. 
I think it was the last RC before releasing the `1.4.0` 

Can you test with your use case please to be sure this issue can be closed ? 

Kr,

**Comment by duke-bartholomew** [comment]
Hi @LGouellec 

Just did a couple of tests (same setup that triggered the issue previously) and now it seems to work correctly.
I did numerous scenarios to trigger rebalances and state restores across multiple instances -- all seem to work :+1: 

Thanks very much for the support! :+1:

**Comment by LGouellec** [comment]
@duke-bartholomew, 

Perfect ! `1.4.0` will be out this week. Stay tuned !

I close the issue 💥
